
version: '3.8'

services:
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./backend/laravel:/var/www/html/backend/laravel
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: CourtControl
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - "8089:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app-network

  laravel:
    build:
      context: ./backend/laravel
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./backend/laravel:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    networks:
      - app-network

  # vue:
  #   build:
  #     context: ./frontend/vue
  #     dockerfile: Dockerfile
  #   container_name: vue_frontend
  #   ports:
  #     - "8081:8081"
  #   volumes:
  #     - ./frontend/vue:/app
  #     - /app/node_modules
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
  #     VUE_APP_WATCH_POLL: "true"
  #   networks:
  #     - app-network



  # react:
  #   build:
  #     context: ./frontend/react
  #     dockerfile: Dockerfile
  #   container_name: react_frontend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend/react:/app
  #     - /app/node_modules
  #   environment:
  #     CHOKIDAR_USEPOLLING: "true"
  #     WATCHPACK_POLLING: "true"
  #   networks:
  #     - app-network

  springboot:
    build:
      context: ./backend/SpringBoot
    container_name: springboot
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/CourtControl
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      JWT_SECRET: "2c4bfa7e7c6b8b320fbb56db9f216b615d0a5b59fd7c1e9c5488a85363c632ef25c05c4d4921fd7e41acdf2278cf6e8335ad9bc132d7f6aab46b50d5280eb1f"
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

