<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonsTableSeeder extends Seeder
{
    public function run()
    {
        DB::table('lessons')->insert([
            [
                'name_class' => 'Tecnificación de Defensa',
                'is_active' => 1,
                'vacancies' => 10,
                'days' => 'L-M-X',
                'time' => '18:00:00',
                'duration' => '01:30:00',
                'base_cost' => 40.00,
                'level' => 'Intermediate',
                'coach' => 'Carlos López',
                'max_capacity' => 15,
                'description' => 'Técnicas de armado, mejora de precisión en pases y jugadas estratégicas.',
            ],
            [
                'name_class' => 'Tecnificación de Recepción',
                'is_active' => 1,
                'vacancies' => 12,
                'days' => 'M-J',
                'time' => '19:00:00',
                'duration' => '01:30:00',
                'base_cost' => 45.00,
                'level' => 'Advanced',
                'coach' => 'Ana Martínez',
                'max_capacity' => 12,
                'description' => 'Entrenamiento de remates, saltos y posicionamiento ofensivo en ataque.',
            ],
            [
                'name_class' => 'Tecnificación de Bloqueo',
                'is_active' => 1,
                'vacancies' => 8,
                'days' => 'X-S',
                'time' => '17:00:00',
                'duration' => '01:20:00',
                'base_cost' => 35.00,
                'level' => 'Beginner',
                'coach' => 'Laura Torres',
                'max_capacity' => 10,
                'description' => 'Técnicas defensivas en bloqueo y control de manos en la red.',
            ],
            [
                'name_class' => 'Tecnificación de Saque',
                'is_active' => 1,
                'vacancies' => 10,
                'days' => 'L-V',
                'time' => '17:30:00',
                'duration' => '01:20:00',
                'base_cost' => 30.00,
                'level' => 'Beginner',
                'coach' => 'David Gómez',
                'max_capacity' => 10,
                'description' => 'Variaciones de saque, precisión y potencia.',
            ],
            [
                'name_class' => 'Tecnificación de Colocación',
                'is_active' => 1,
                'vacancies' => 12,
                'days' => 'M-J',
                'time' => '18:00:00',
                'duration' => '01:30:00',
                'base_cost' => 40.00,
                'level' => 'Intermediate',
                'coach' => 'Carlos López',
                'max_capacity' => 15,
                'description' => 'Mejora en técnicas de colocación y organización del ataque.',
            ],
            [
                'name_class' => 'Tecnificación de Remate',
                'is_active' => 1,
                'vacancies' => 8,
                'days' => 'X-V',
                'time' => '17:00:00',
                'duration' => '01:20:00',
                'base_cost' => 45.00,
                'level' => 'Advanced',
                'coach' => 'Ana Martínez',
                'max_capacity' => 10,
                'description' => 'Potenciación de remates y trabajo de coordinación ofensiva.',
            ],
            [
                'name_class' => 'Tecnificación de Salto',
                'is_active' => 1,
                'vacancies' => 15,
                'days' => 'L-M',
                'time' => '18:30:00',
                'duration' => '01:30:00',
                'base_cost' => 35.00,
                'level' => 'Intermediate',
                'coach' => 'Laura Jiménez',
                'max_capacity' => 20,
                'description' => 'Mejora de salto y potencia para todas las posiciones.',
            ],
            [
                'name_class' => 'Tecnificación de Tiro',
                'is_active' => 1,
                'vacancies' => 10,
                'days' => 'M-J',
                'time' => '19:30:00',
                'duration' => '01:40:00',
                'base_cost' => 50.00,
                'level' => 'Intermediate',
                'coach' => 'Luis Fernández',
                'max_capacity' => 15,
                'description' => 'Técnicas de tiro en movimiento y desde la línea de tres puntos.',
            ],
            [
                'name_class' => 'Tecnificación de Defensa',
                'is_active' => 1,
                'vacancies' => 12,
                'days' => 'X-S',
                'time' => '18:00:00',
                'duration' => '01:10:00',
                'base_cost' => 25.00,
                'level' => 'Intermediate',
                'coach' => 'Luis Fernández',
                'max_capacity' => 15,
                'description' => 'Trabajo defensivo en la pintura y control de rebotes.',
            ],
            [
                'name_class' => 'Pliometría - Potencia',
                'is_active' => 1,
                'vacancies' => 20,
                'days' => 'M-V',
                'time' => '19:30:00',
                'duration' => '01:10:00',
                'base_cost' => 25.00,
                'level' => 'Advanced',
                'coach' => 'Jorge Álvarez',
                'max_capacity' => 25,
                'description' => 'Entrenamiento de salto, ejercicios de explosividad y mejora de potencia física.',
            ],
            [
                'name_class' => 'Entrenamiento funcional',
                'is_active' => 1,
                'vacancies' => 25,
                'days' => 'L-M-V',
                'time' => '19:30:00',
                'duration' => '01:15:00',
                'base_cost' => 30.00,
                'level' => 'Beginner',
                'coach' => 'Carla Torres',
                'max_capacity' => 30,
                'description' => 'Circuitos funcionales para mejorar fuerza, resistencia y estabilidad general.',
            ],
            [
                'name_class' => 'Tecnificación de Coordinación',
                'is_active' => 1,
                'vacancies' => 15,
                'days' => 'M-J',
                'time' => '16:30:00',
                'duration' => '01:15:00',
                'base_cost' => 40.00,
                'level' => 'Beginner',
                'coach' => 'Ana Martínez',
                'max_capacity' => 20,
                'description' => 'Ejercicios específicos para mejorar la coordinación óculo-manual y el control corporal.',
            ],
            [
                'name_class' => 'Tecnificación de Pase',
                'is_active' => 1,
                'vacancies' => 12,
                'days' => 'L-V',
                'time' => '17:30:00',
                'duration' => '01:20:00',
                'base_cost' => 35.00,
                'level' => 'Intermediate',
                'coach' => 'David Gómez',
                'max_capacity' => 15,
                'description' => 'Precisión y velocidad en pases bajo presión.',
            ],
            [
                'name_class' => 'Tecnificación de Bote Balón',
                'is_active' => 1,
                'vacancies' => 12,
                'days' => 'X-S',
                'time' => '17:30:00',
                'duration' => '01:20:00',
                'base_cost' => 55.00,
                'level' => 'Intermediate',
                'coach' => 'Stephen Curry',
                'max_capacity' => 30,
                'description' => 'Precisión y calidad del bote en movimiento.',
            ],
        ]);
    }
}
