const Constant = {
    // Loading states
    SET_LOADING: 'SET_LOADING',
    SET_ERROR: 'SET_ERROR',
    
    // Sport actions
    INITIALIZE_SPORT: 'INITIALIZE_SPORT',
    INITIALIZE_ONE_SPORT: 'INITIALIZE_ONE_SPORT',
    DELETE_SPORT: 'DELETE_SPORT',
    UPDATE_SPORT: 'UPDATE_SPORT',
    ADD_SPORT: 'ADD_SPORT',
    
    // Material actions
    INITIALIZE_MATERIAL: 'INITIALIZE_MATERIAL',
    INITIALIZE_ONE_MATERIAL: 'INITIALIZE_ONE_MATERIAL',
    DELETE_MATERIAL: 'DELETE_MATERIAL',
    UPDATE_MATERIAL: 'UPDATE_MATERIAL',
    ADD_MATERIAL: 'ADD_MATERIAL',
    
    // Dashboard specific
    FETCH_DASHBOARD_SPORTS: 'FETCH_DASHBOARD_SPORTS',
    FETCH_DASHBOARD_MATERIALS: 'FETCH_DASHBOARD_MATERIALS',
    SET_DASHBOARD_MODE: 'SET_DASHBOARD_MODE',
    
    // API Status codes
    STATUS_OK: 200,
    STATUS_CREATED: 201,
    STATUS_BAD_REQUEST: 400,
    STATUS_UNAUTHORIZED: 401,
    STATUS_FORBIDDEN: 403,
    STATUS_NOT_FOUND: 404
};

export default Constant;
